export enum CharacterClass {
    UNKNOWN,
    ARTILLERIST,
    BARD,
    BERSERKER,
    DEADEYE,
    DEATHBLADE,
    DESTROYER,
    GLAIVIER,
    GUNLANCER,
    GUNSLINGER,
    PALADIN,
    SCRAPPER,
    SHADOWHUNTER,
    SHARPSHOOTER,
    SORCERESS,
    SOULFIST,
    STRIKER,
    WARDANCER,
}

export enum DailyTrackerType {
    CHAOS,
    GUARDIAN,
    UNA_TASK,
    GUILD_DONATION,
}